name: "Publish documentation"
on:
  workflow_run:
    workflows:
      - "Build and push documentation on main"
    types:
      - completed

jobs:
  publish-documentation:
    name: Publish documentation
    permissions:
      id-token: "write"
      pages: "write"

    runs-on: "ubuntu-latest"

    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v3"
        with:
          ref: "documentation"

      - id: "upload-documentation"
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v2"
        with:
          path: "docs/"

      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v2"

